version: 0.2

env:
  parameter-store:
    ssh_key: id_ed25519
    ssh_pub: id_ed25519.pub


phases:
  install:
    commands:
      - mkdir -p ~/.ssh
      - echo "$ssh_key" > ~/.ssh/id_ed25519   
      - echo "$ssh_pub" > ~/.ssh/id_ed25519.pub
      - chmod 600 ~/.ssh/id_ed25519
      - eval "$(ssh-agent -s)"
      - git submodule update --init --recursive
