version: 0.2

env:
   parameter-store:
    ssh_key: id_ed25519 
    ssh_pub: id_ed25519.pub

phases:
  install:
    commands:
      - mkdir -p ~/.ssh
      - echo "$ssh_key" > ~/.ssh/id_ed25519
      - echo "$ssh_pub" > ~/.ssh/id_ed25519.pub
      - chmod 600 ~/.ssh/id_ed25519
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - git init
      - git submodule add git@github.com:rameshreddy799/awscodebuildsubmodule2.git
      - git status
      - git diff --cached --submodule
      - git config --global user.email "rameshreddy799@gmail.com"
      - git config --global user.name "rameshreddy799"
      - git commit -m 'Add aws sub module1'
      - git remote -v
      - git remote add origin git@github.com:rameshreddy799/awsgithubcodebuild.git
      - git fetch origin master:tmp
      - git rebase tmp
      - git push origin HEAD:master
      - git branch -D tmp
  build:
    commands:
      - echo '...replace with real build commands...'

artifacts:
  files:
    - '**/*'
