version: 0.2

env:
   parameter-store:
    ssh_key: id_ed25519 
    ssh_pub: id_ed25519.pub

phases:
  install:
    commands:
      - mkdir -p ~/.ssh
      - echo "$ssh_key" > ~/.ssh/id_ed25519
      - echo "$ssh_pub" > ~/.ssh/id_ed25519.pub
      - chmod 600 ~/.ssh/id_ed25519
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - git init
      - git remote add origin https://github.com/rameshreddy799/awscodebuildgitsubmodule1.git
      - git fetch
      - git checkout -t origin/master
      - git submodule init
      - git submodule update --recursive
  build:
    commands:
      - echo '...replace with real build commands...'

artifacts:
  files:
    - '**/*'
